// PreactProject/src/pages/About.jsx
/* eslint-disable react/no-unescaped-entities */
import Header from '../components/Header/Header';
import Image from '../components/Image/Image';
import TextContainer from '../components/TextContainer/TextContainer';

const About = () => {
	return (
		<>
			<Header />
      <Image src='https://hedclub.com/data/pub/113/swUZP6CJ_9aiAEiE4-w3.jpg' />
      <TextContainer />
		</>
	);
};

export default About;

// VueProject/src/pages/About/About.vue
<template>
  <Header />
  <Image src='https://hedclub.com/data/pub/113/swUZP6CJ_9aiAEiE4-w3.jpg' />
  <TextContainer />
</template>

<script>
import Header from '../../components/Header/Header.vue';
import Image from '../../components/Image/Image.vue';
import TextContainer from '../../components/TextContainer/TextContainer.vue';

export default {
  components: {
    Header,
    Image,
    TextContainer
  },
}

</script>

<style></style>
